#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fake_news_index:
  path: /
  controller: App\Controller\NewsController::accueil

fake_news_accueil:
  path: /accueil
  controller: App\Controller\NewsController::accueil
